// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.1; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------------ //
// emmc_dat0_rx //
// ------------ //

#define emmc_dat0_rx_wrap_target 0
#define emmc_dat0_rx_wrap 6
#define emmc_dat0_rx_pio_version 0

static __pio_const uint16_t emmc_dat0_rx_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1
    0x7820, //  1: out    x, 32           side 1
    0xb042, //  2: nop                    side 0
    0x18c2, //  3: jmp    pin, 2          side 1
    0xb042, //  4: nop                    side 0
    0x5001, //  5: in     pins, 1         side 0
    0x1844, //  6: jmp    x--, 4          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program emmc_dat0_rx_program = {
    .instructions = emmc_dat0_rx_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = emmc_dat0_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config emmc_dat0_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + emmc_dat0_rx_wrap_target, offset + emmc_dat0_rx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

