#!/usr/bin/env python3
import argparse
from datetime import datetime
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate build_info.h with build timestamp macros")
    ap.add_argument("--output", required=True, help="Path to generated header")
    args = ap.parse_args()

    now = datetime.now()
    date_s = f"{now:%b} {now.day:2d} {now:%Y}"
    time_s = f"{now:%H:%M:%S}"
    iso_s = f"{now:%Y-%m-%dT%H:%M:%S}"

    out = (
        "// Auto-generated by tools/gen_build_info.py\n"
        "#ifndef BROWSERIO_BUILD_INFO_H_\n"
        "#define BROWSERIO_BUILD_INFO_H_\n\n"
        f'#define BROWSERIO_BUILD_DATE "{date_s}"\n'
        f'#define BROWSERIO_BUILD_TIME "{time_s}"\n'
        f'#define BROWSERIO_BUILD_ISO_LOCAL "{iso_s}"\n\n'
        "#endif\n"
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
